FROM golang:latest

# Change this path!
WORKDIR /app
# RUN mkdir /opt/src
# COPY main /opt/src

COPY . /app
# RUN go mod tidy
# RUN go build -0 main .

RUN go mod download

RUN go build -o app
# WORKDIR /opt/src
EXPOSE 3000
# RUN ls
# CMD ["./main"]
CMD ["/app/app"]